### ISSUE TITLE
How to avoid "null" value when filtering non-exist keys?

### ISSUE THREAD

**Issue by suxpert** [stedolan/jq#1583] opened 2018-01-24 11:32 UTC
Let's say, e.g., I have multiple similar json files like this:
```json
{
    "foo": 1,
    "bar": 1,
    "baz": 1,
    "foobar": 1,
    "others": "I don't need"
}
```
Now I need to clean up those json files, leaving only `foo, bar, baz, foobar` in the new json files.

If I do this:
```bash
$ jq '{foo,bar,baz,foobar}' input.json > output.json
```
Then if there are no "foobar" in the input json file, there will be
```json
    "foobar", null
```
in the output file.

So here is the question, is there any easier way in doing such a filter?

**Comment by nicowilliams** [comment] 2018-02-20 22:02
In jq the array/object index operation will yield `null` if the key is not present.

There's an open issue where I propose a `!` operator to make the index operation produce an error if the key is not found, then `.key!` would produce an error if `"key"` is not present, and this would combine well with the `?` operator so that `.key!?` would produce `empty` when the key is not present.

You can do what you want if you're willing to have more verbosity:

```
$ jq '. as $object | reduce (["foo","bar","baz","foobar"] as $keys | keys_unsorted[] | select(. == $keys[])) as $key ({}; .[$key] = $object[$key])'
```

Or something like that.  You can also use `has` to do something similar.

When we do add a `!` operator we'll want to make sure it also works in object constructor syntax, so you'd say `jq '{foo!?,bar!?,baz!?,foobar!?}'`...
```

**Comment by nicowilliams** [comment] 2018-02-20 22:03
This is basically a duplicate of #859.

**Closed** 2018-02-20 22:03 UTC
Labels: dup

**Comment by pkoppstein** [comment] 2018-02-20 22:22
@suxpert - Here's a reduce-free approach that allows you to build on the simplicity of {foo,bar,bar,foobar}.

```
def cleanup: with_entries(if .value == null then empty else . end);

{foo,bar,baz,foobar}
| cleanup 
```

**Comment by nicowilliams** [comment] 2018-02-20 23:47
@pkoppstein That only works if the original did not have those keys present with `null` values..

**Comment by pkoppstein** [comment] 2018-02-21 00:29
@nicowilliams - Yes, I should have made that clear. I've added a clarifying statement accordingly. Thanks.
