### ISSUE TITLE
File names with non ASCII characters

### ISSUE THREAD

**Issue by svnpenn** [stedolan/jq#811] opened 2015-06-13 23:17 UTC
Running on master gives me this error:

~~~
$ jq . róisín.json
jq: error: Could not open file r�is�n.json: No such file or directory
~~~

Running a git bisect reveals this:

~~~
0d414471bb41f41373754c680ecc7f955a9ec2ad is the first bad commit
commit 0d414471bb41f41373754c680ecc7f955a9ec2ad
Author: Nicolas Williams <nico@cryptonector.com>
Date:   Sun Feb 1 18:35:42 2015 -0600
Refactor moar: move parts of main.c into libjq
~~~

I dont know how, but 0d41447 is the culprit. Just to confirm, I ran:

~~~
git checkout 0d41447
~~~

and it errors as expected, then ran:

~~~
git checkout 0d41447^
~~~

and it gives desired result:

~~~json
$ jq . róisín.json
{
  "alpha": "bravo"
}
~~~

Please look into this @nicowilliams , as I would like to be able to use non
ASCII characters sometimes.

**Comment by nicowilliams** [comment] 2015-06-14 03:56
I'm travelling but i think i know what did it.  You're not in a Unicode
locale, right?

**Comment by svnpenn** [comment] 2015-06-14 04:12
I am on Windows but everything should be UTF-8

~~~
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=

$ chcp.com
Active code page: 65001
~~~

**Comment by nicowilliams** [comment] 2015-06-14 21:41
Do you have an od(1)?.  The key is: what encoding is the input method is
producing?

The change, IIRC, was to use jv arrays too keep track of the filenames.  If
the input isn't UTF-8...

**Comment by svnpenn** [comment] 2015-06-14 21:54
Upon more research, it appears the problem is much deeper. Before 0d41447 non ASCII characters worked on Windows, but only if they were in Windows-1252 code page. Any characters outside of that code page fail on all versions of JQ.

The solution to this would be to implement an `#if` statement that includes a call to `GetCommandLineW` as mentioned here

http://stackoverflow.com/questions/30832756/accept-non-ascii-characters

I found an implementation of this in the FFmpeg project if it helps

http://github.com/FFmpeg/FFmpeg/blob/ec5164a/cmdutils.c#L221-L281

**Comment by svnpenn** [comment] 2015-06-15 00:46
I wrote a simple function to get UTF-8 arguments, only 19 lines

http://stackoverflow.com/a/30836010

**Comment by nicowilliams** [comment] 2015-06-15 04:59
I see.  Thanks for root-causing this.

**Comment by nicowilliams** [comment] 2015-06-15 05:31
Send me a PR and I'll merge it.  Do you reckon we go for a single-allocation here?  If so, why not just use `alloca()` and put the argv constructor in `main()` itself and avoid any heap allocations...?

**Comment by svnpenn** [comment] 2015-06-15 05:33
It looks like it might be easier to use `#ifdef` with `main()`/`wmain()`. I am looking into it

**Comment by svnpenn** [comment] 2015-06-15 06:27
Here is an example of printing a Unicode string, and opening a Unicode filename:

    #include <fcntl.h>
    #include <stdio.h>

    int wmain (int argc, wchar_t** argv) {
      _setmode(_fileno(stdout), _O_WTEXT);
      wprintf(L"%s\n", argv[1]);
      _wopen(argv[1], _O_RDONLY);
      return 0;
    }

**Comment by nicowilliams** [comment] 2015-06-15 06:41
Then I'd rather not use wmain().

**Comment by svnpenn** [comment] 2015-06-15 12:04
You can do this:

~~~c
#ifdef WIN32
int wmain (int argc, wchar_t** argv) {
#else
int main(int argc, char* argv[]) {
#endif
~~~

**Comment by nicowilliams** [comment] 2015-06-15 16:07
> You can do this:

No, I'd rather take your first design.  I may just use alloca() in
main() and be done.

**Comment by nicowilliams** [comment] 2015-06-15 16:42
How about this, in `main()`:

    #ifdef WIN32
      int wargc;
      wchar_t **wargv = CommandLineToArgvW(GetCommandLineW(), &argc);
      assert(wargc == argc);
      for (int i = 0; i < argc; i++) {
        argv[i] = alloca(WideCharToMultiByte(CP_UTF8, 0, argv_utf16[i], -1, 0, 0, 0, 0));
        WideCharToMultiByte(CP_UTF8, 0, argv_utf16[i], -1, argv[i], size-offset, 0, 0);
      }
    #endif

Does that work for you?  It's a bit hacky, I know, but hey.

We should probably ifdef on Mingw as well.

**Comment by nicowilliams** [comment] 2015-06-15 16:46
(And if loc matters, that's only 9 loc.  :)  Also, perhaps we do want to ask for precomposition (WC_COMPOSITECHECK) and other options (WC_DEFAULTCHAR and WC_DISCARDNS).

Most input methods produce pre-composed Unicode, so decomposing when going from UTF-16 to UTF-8 will break simple string comparisons.  File name matching will only work if the filesystem decomposes (IIUC only OS X's HFS+ does this) or if the filesystem does normalization-insensitive file name comparison (IIUC only ZFS does this).

**Comment by svnpenn** [comment] 2015-06-15 17:39
@nicowilliams as long as it works, I am fine with it. Just make let me know if you have a patch so I can test. Using `GetCommandLineW` can be tricky because you have to convert back to UTF-16 if you want to actually open a file rather than printing a string. I have a code sample for that if needed.

**Comment by nicowilliams** [comment] 2015-06-15 19:07
So, this is partly a function of Mingw.  Is there a way to ask Mingw to assume strings (e.g., passed to open(), fopen(), *printf(), ...) are UTF-8?

**Comment by nicowilliams** [comment] 2015-06-15 19:20
Oh, there appear to be fundamental, severe brokenness with UTF-8 support in the Windows console, with low-level I/O routines that normally deal in counts of bytes instead using counts of characters (that's what I see in various threads, but I bet it's numbers of codepoints).  There's no completely sane way to work around such problems, so I'm inclined to make this an FAQ/wontfix, though I'll accept a PR that isolates the damage well enough.

http://stackoverflow.com/questions/27580018/mingw-gcc-on-windows-and-utf-8-characters
https://social.msdn.microsoft.com/Forums/vstudio/en-US/e4b91f49-6f60-4ffe-887a-e18e39250905/possible-bugs-in-writefile-and-crt-unicode-issues?forum=vcgeneral
http://stackoverflow.com/questions/388490/unicode-characters-in-windows-command-line-how
http://stackoverflow.com/questions/10882277/how-to-properly-print-utf8-characters-in-windows-console
http://stackoverflow.com/questions/9611931/whats-your-utf-8-console-setting-when-programming-google-go-under-windows

**Comment by nicowilliams** [comment] 2015-06-18 05:17
I think I'd rather go back to a hand-coded array instead of a jv array in the input utils to restore this functionality without much more fuss, and then ignore all issues to do with console UTF-8 non-support.

**Comment by svnpenn** [comment] 2015-06-18 11:53
At least give me a chance to write a patch. If FFmpeg project can do it, then I should be able to

**Comment by nicowilliams** [comment] 2015-06-18 15:11
The problem is that shoving filenames into a jv array assumes that the locale is a UTF-8 locale, which it might not be.  So it's not just Windows.

Of course, if you use jq in a non-UTF-8 locale then the JSON it consumes and emits might not work well on stdin/stdout, but users aren't required to use stdin/stdout, so I think the right thing to do is to go back to a hand-coded array.  I'm sure you can write a good patch that does what you propose, but this seems more general.

**Comment by svnpenn** [comment] 2015-06-18 17:55
To me, only support ASCII filenames is "not good enough". Supporting UTF-8 filenames is "good enough". If I can implement that, and someone has a filename outside of UTF-8, then that is their problem IMO

**Comment by nicowilliams** [comment] 2015-06-18 18:35
I think we can distinguish "non-ASCII as to filenames" and "non-ASCII as to contents".

There isn't anything we can do about the latter, except in raw output mode we could iconv from UTF-8 to the current locale's codeset (and the converse for raw input mode) -- JSON is Unicode.  (I suppose jq could support UTF-16 and UTF-32 for JSON interchange, but I don't see why, so UTF-8 is it for JSON interchange.)

But filenames given on the command line are not part of any JSON texts.  So at the very least we can handle those differently.

Which reminds me: the `input_filename` builtin is also going to be affected.  I don't relish having to use any locale functions, or iconv(), just to make `input_filename` work.  We could just remove it...  Then use a hand-coded array for filenames, and that's that.  I'd still like to see your patch though, if you have it ready or nearly so -- it might change my mind.

**Comment by svnpenn** [comment] 2015-06-18 23:03
Please confirm: the original issue, and my only current concern is non ASCII **filenames**. The issue of non ASCII content is a separate issue that I have not addressed, if it even needs addressing

**Comment by nicowilliams** [comment] 2015-06-18 23:33
On Thu, Jun 18, 2015 at 04:03:02PM -0700, Steven Penny wrote:
> Please confirm: the original issue, and my only current concern is non ASCII **filenames**. The issue of non ASCII content is a separate issue that I have not addressed, if it even needs addressing

Correct.  I don't think the latter needs addressing.

**Comment by nicowilliams** [comment] 2015-06-19 02:37
@svnpenn FYI, my fix is ready to go; I'll push it momentarily.  If you have a more general fix that converts between encodings, I'd like to consider it; we can always revert my fix and apply yours.

**Comment by svnpenn** [comment] 2015-06-19 04:18
That fix does not fix it...

~~~
$ jq --version
jq-1.5rc1-111-g292f2d3-dirty

$ jq . /Ω.json
jq: error: Could not open file ../O.json: No such file or directory
~~~

**Comment by nicowilliams** [comment] 2015-06-19 04:52
Actually, it works.  It's just the error message that's wrong.  If the file exists jq will read it.

Mind you, I'd like to know what's wrong here.

**Comment by nicowilliams** [comment] 2015-06-19 05:53
I added a printf to print the argument before anything else happens, and indeed, it just gets printed wrong.  That, I think, has to do with mingw converting arguments to ANSI, right?  It's late.  I'll revisit this this weekend, re-read the links above.  So, yeah, I think we need to build our own argument vector from the wide char version.

**Comment by svnpenn** [comment] 2015-06-19 11:56
As I have said, it is not just printing wrong, but a systemic problem. Unless we use `wmain` with `#ifdef` or `GetCommandLineW`, command line argument will be converted to ANSI and fail spectacularly when `printf`ed or `fopen`ed

**Comment by nicowilliams** [comment] 2015-06-19 16:02
Yes, we'll need to use `GetCommandLineW()`.

The change I pushed is still desirable on Unix systems, so I'll leave that much as is.

**Comment by nicowilliams** [comment] 2015-06-19 23:29
This:

    #ifdef WIN32
      int wargc;
      wchar_t **wargv = CommandLineToArgvW(GetCommandLineW(), &wargc);
      assert(wargc == argc);
      size_t arg_sz;
      for (int i = 0; i < argc; i++) {
        argv[i] = alloca((arg_sz = WideCharToMultiByte(CP_UTF8,
                                                       0, wargv[i], -1, 0, 0, 0, 0)));
        WideCharToMultiByte(CP_UTF8, 0, wargv[i], -1, argv[i], arg_sz, 0, 0);
      }
    #endif

builds and runs, and I can see that `WideCharToMultiByte()` outputs the correct results (I did have to end up passing 0 as `dwFlags`).

The output of debug printfs is all wrong, whether I'm printing wide char strings or plain char strings.  If I run the same executable in a cygwin shell then the plain char strings do display correctly, and... ah!  if I make sure I switch to the UTF-8 codepage, then the cmd.exe shell displays plain strings correctly (but still not wide char strings; go figure).

But now jq definitely cannot find the file, which I gather must be a problem with mingw.

Now we just need a way to open files with UTF-8 names.

This is dispiriting:

http://mingw-users.1079350.n2.nabble.com/Unicode-file-names-td3205731.html

I guess we need an `fopen()` wrapper around `_wfopen()`.  Mingw ought to have its own.

Well, enough for now.  That's a modicum of progress.  We know how to get a UTF-8 argv.

**Comment by svnpenn** [comment] 2015-06-19 23:44
As my above post shows, this will work with `wmain`:

~~~c
#include <fcntl.h>

int wmain (int argc, wchar_t** argv) {
  _wopen(argv[1], _O_RDONLY);
  return 0;
}
~~~

However without `wmain` it takes much more:

~~~c
#include <fcntl.h>
#include <windows.h>

int get_argv_utf8(int* argc_ptr, char*** argv_ptr) {
  int argc;
  char** argv;
  wchar_t** argv_utf16 = CommandLineToArgvW(GetCommandLineW(), &argc);
  int i;
  int offset = (argc + 1) * sizeof(char*);
  int size = offset;
  for (i = 0; i < argc; i++)
    size += WideCharToMultiByte(CP_UTF8, 0, argv_utf16[i], -1, 0, 0, 0, 0);
  argv = malloc(size);
  for (i = 0; i < argc; i++) {
    argv[i] = (char*) argv + offset;
    offset += WideCharToMultiByte(CP_UTF8, 0, argv_utf16[i], -1,
      argv[i], size-offset, 0, 0);
  }
  *argc_ptr = argc;
  *argv_ptr = argv;
  return 0;
}

int utf8towchar(char* filename_utf8, wchar_t** filename_w) {
  int num_chars = MultiByteToWideChar(CP_UTF8, 0, filename_utf8, -1, 0, 0);
  int size = sizeof(wchar_t);
  *filename_w = malloc(size);
  MultiByteToWideChar(CP_UTF8, 0, filename_utf8, -1, *filename_w, num_chars);
  return 0;
}

int main(int argc, char** argv) {
  wchar_t* filename_w;
  get_argv_utf8(&argc, &argv);
  utf8towchar(argv[1], &filename_w);
  _wopen(filename_w, _O_RDONLY);
  return 0;
}
~~~

**Comment by nicowilliams** [comment] 2015-06-19 23:54
But everywhere else we deal with `char *`.  So conversions from `wchar_t *` to `char *` are a given anyways.

Adding a wrapper around `_wfopen()` takes care of the last remaining issue.

**Closed** 2015-06-19 23:55 UTC
Labels: bug

**Comment by nicowilliams** [comment] 2015-06-19 23:59
@svnpenn Please test master.  It works for me.  My cmd.exe window starts with codepage 437 and prints garbled filenames unless I switch to codepage 65001, otherwise it all just works (either way it finds files with non-ASCII characters).

**Comment by nicowilliams** [comment] 2015-06-20 00:00
I suppose I could fix the one place where we print filenames to convert those back to widechar strings and then use "%ls".

**Comment by svnpenn** [comment] 2015-06-20 00:01
You did it! Excellent!

~~~
$ jq --version
jq-1.5rc1-114-g7811ef1-dirty

$ jq . Ω.json
{
  "alpha": "bravo"
}
~~~

**Comment by nicowilliams** [comment] 2015-06-20 00:01
:)

**Comment by svnpenn** [comment] 2015-06-20 00:02
and yes, the code page does need to be 65001. In my opinion if the user does not
have that set, then it is their problem

**Comment by nicowilliams** [comment] 2015-06-20 00:03
I am thoroughly disgusted though.  I need a shower now.

**Comment by svnpenn** [comment] 2015-06-21 00:13
#824

**Comment by svnpenn** [comment] 2015-09-06 23:31
#939

**Comment by svnpenn** [comment] 2015-09-06 23:35
#262

**Comment by svnpenn** [comment] 2016-08-16 21:11
https://github.com/svnpenn/mp4v2/issues/186

**Comment by svnpenn** [comment] 2016-12-09 12:16
https://github.com/Martchus/tageditor/issues/15

**Comment by svnpenn** [comment] 2016-12-09 12:44
https://github.com/Martchus/tageditor/issues/4

**Comment by svnpenn** [comment] 2017-03-21 12:10
https://github.com/Martchus/tageditor/issues/18

**Comment by svnpenn** [comment] 2017-08-17 02:33
https://github.com/Martchus/tageditor/issues/21
