### ISSUE TITLE
Consider making '.' the default when no filters specified

### ISSUE THREAD

**Issue by rfreebern** [stedolan/jq#1040] opened 2015-12-10 17:09 UTC
When piping output through jq for pretty-printing, it gets cumbersome to type `jq '.'` every single time. It would be nice if `'.'` was the default when no filter was specified and there is input on STDIN.

**Comment by nicowilliams** [comment] 2015-12-10 17:10
Duplicate of #1028.

**Closed** 2015-12-10 17:10 UTC
Labels: dup, fixed in master

**Comment by dtolnay** [comment] 2015-12-10 17:12
Not quite a duplicate. This is already the behavior in jq 1.5.

**Comment by nicowilliams** [comment] 2015-12-10 17:13
Ah, good point.  Still, it's a duplicate of some other issue then.

**Comment by rfreebern** [comment] 2015-12-10 17:53
Oh, thanks! Sorry, I read the docs but didn't see this behavior mentioned, and most examples still use `jq '.'`. Glad to know all I need to do is upgrade!
