### ISSUE TITLE
jq error: cannot allocate memory

### ISSUE THREAD

**Issue by sk8rgal** [stedolan/jq#1815] opened 2019-02-08 09:16 UTC
```
$ echo '""' | jq 'index("")'
error: cannot allocate memory
Aborted (core dumped)
```

**Comment by nicowilliams** [comment] 2019-02-08 17:50
Good find!  Thanks for the report!

**Comment by pkoppstein** [comment] 2019-02-08 17:56
FYI, this is not a problem on MacOS X. I've checked using jq 1.4, 1.5, 1.6 and current Master.

**Comment by muhmuhten** [comment] 2019-02-09 01:37
Does `jq -n '"x"|_strindices("")'` (or really `_strindices("")` on any string) on OS X not hang as jq tries to stick 0s onto an array forever?

**Comment by nicowilliams** [comment] 2019-02-09 02:35
Ultimately the problem is that we call `_jq_memmem()` with zero for the needle length -- this is not safe.

**Comment by nicowilliams** [comment] 2019-02-09 02:38
```
diff --git a/src/jv.c b/src/jv.c
index f051d73..b3fcd5e 100644
--- a/src/jv.c
+++ b/src/jv.c
@@ -658,6 +658,8 @@ jv jv_string_indexes(jv j, jv k) {
   int idxlen = jv_string_length_bytes(jv_copy(k));
   jv a = jv_array();

+  if (idxlen == 0)
+    return a;
   p = jstr;
   while ((p = _jq_memmem(p, (jstr + jlen) - p, idxstr, idxlen)) != NULL) {
     a = jv_array_append(a, jv_number(p - jstr));
```

is my fix for this.

**Closed** 2019-02-09 02:41 UTC
Labels: bug
