### ISSUE TITLE
json processing error

### ISSUE THREAD

**Issue by UesugiErii** [stedolan/jq#2442] opened 2022-06-17 09:22 UTC
**Describe the bug**
json process error

**To Reproduce**
`echo '{"a":[10000000000000007],"b":{"10000000000000007":2}}' | jq`

**Expected behavior**
<img width="591" alt="捕获" src="https://user-images.githubusercontent.com/24751316/174268932-d9acee85-31a0-482a-8dbf-738fa37e2029.PNG">

**Environment (please complete the following information):**
 - OS and Version: Ubuntu 20.04.4 LTS
 - jq version1.6

**Additional context**
When the number is greater than 10000000000000000, the result is possible +1 or -1 or dont change

**Comment by superhawk610** [comment] 2022-09-09 22:09
I ran into the same issue - we use large numbers as IDs. The numbers appear to be off by a random amount:

```shell
$ echo '{"userId":288158953888548720}' | jq  # off by 20
{
  "userId": 288158953888548740
}

$ echo '{"userId":933278756423858111}' | jq  # off by 111
{
  "userId": 933278756423858000
}
```

It seems like whatever data type `jq` stores numeric values in isn't large enough, perhaps?

**Comment by superhawk610** [comment] 2022-09-09 22:17
Seems that this is a duplicate of #1652.

**Closed** 2022-09-11 08:39 UTC
