### ISSUE TITLE
Invalid json file returns no output, exit code 0

### ISSUE THREAD

**Issue by pshahid** [stedolan/jq#792] opened 2015-05-21 20:09 UTC
Given this file test.json (intentional missing brace): 

```json
{
    "a": "b",
    "c": true,
    "d": 0
```

And this command:

```bash
jq . test.json
```

jq will not echo any output and the exit status is 0.

**Comment by nicowilliams** [comment] 2015-05-21 20:26
This is fixed in master.

**Closed** 2015-07-25 07:42 UTC
Labels: fixed in master

**Comment by dtolnay** [comment] 2015-07-25 07:45
Duplicate of #769.
