### ISSUE TITLE
jq mangles floats

### ISSUE THREAD

**Issue by travisbrady** [stedolan/jq#627] opened 2014-11-24 22:49 UTC
I often use jq to filter json before piping to other programs and those other programs die when they hit examples like this:

```bash
$ echo '{"id" : 1241000000}' | jq '.'
{
  "id": 1.241e+09
}
```

**Comment by dtolnay** [comment] 2015-07-25 04:27
Closing as a duplicate of #218.

**Closed by dtolnay** 2015-07-25 04:27 UTC
Labels: feature request
