### ISSUE TITLE
Broken cyrillic in string literals.

### ISSUE THREAD

**Issue by agolovko1-at-tinkoff-ru** [stedolan/jq#1311] opened 2017-01-19 11:00 UTC
File example: [jq.txt](https://github.com/stedolan/jq/files/716344/jq.txt).
Command: `jq -n -f jq.txt`.

I expect that output contains equal strings under the paths `validation.rules.rule3.errorMessages.regexNotMatched` and `validation.rules.rule4.errorMessages.regexNotMatched`, but `rule3` contains altered 5th symbol (and it does not seem to be valid utf8 codepoint).

Similar replacements somewhere in first two words occure with modifications in the 7th line (marked with comment "magic line"), if a) remove comment (with space after comma), b) remove text except leading six spaces, c) remove all text, leaving blank line.

jq-1.5rc2-152-g0b82185 (and same errors with jq-1.5 from Centos 7 repository).

Linux 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

--
Alexey Golovko, a.golovko1@tinkoff.ru

**Comment by pkoppstein** [comment] 2017-01-19 16:39
The two strings in jq.txt are NOT the same, which you can see by using `explode`, e.g. by modifying the very last line of jq.txt to

off_step_2
| ( (.validation.rules.rule3.errorMessages.regexNotMatched | explode)
  ,
  (.validation.rules.rule4.errorMessages.regexNotMatched | explode)
)

The first string contains two occurrences of

     'REPLACEMENT CHARACTER' (U+FFFD)
 
This character (UTF-32 (decimal) 65533) does not appear in the second string.

You can read about U+FFFD, which appears in the "specials" block, at http://www.fileformat.info/info/unicode/char/0fffd/index.htm

**Comment by agolovko1-at-tinkoff-ru** [comment] 2017-01-23 07:16
These replacement symbols are added by jq itself. These lines are identical in jq.txt.

You can verify this with `grep regexNotMatched jq.txt | tail -n1 | head -n1 | md5sum` and `grep regexNotMatched jq.txt | tail -n2 | head -n1 | md5sum`.

Even your variant with explode returns the same results, if you remove (unused) definition for off_step_1.

**Comment by pkoppstein** [comment] 2017-01-23 10:47
@agolovko1-at-tinkoff-ru - You are right!  This is weirder than anything else I've seen using jq, which is why I was looking for a "simple" explanation.  Thanks for pressing the issue.

**Comment by nicowilliams** [comment] 2017-01-23 18:05
curl -Lg https://github.com/stedolan/jq/files/716344/jq.txt|less

Doesn't look like UTF-8 to me.

**Comment by pkoppstein** [comment] 2017-01-23 18:58
@nicowilliams - Glad to see you back in jq land.

Regarding this particular issue, I think @agolovko1-at-tinkoff-ru has indeed uncovered a weird bug.

First, as I mentioned, isutf8 does indicate the entire file is UTF-8, and I cannot see any part that isn't.

Second, it's weird that including an irrelevant `def` should result in erroneous behavior of an independent `def`.

In any case, if there were something in the file that isn't UTF-8 but that is causing problems, one would hope that jq would issue some kind of warning or error message.

Could it be that the ff48bd6 update exposes some arcane memory management issue?

**Comment by wtlangford** [comment] 2017-01-23 20:00
I actually played with this the other day and forgot to respond.  Try
adding a single space to the front of the file and running it.
`jq -n -f <(cat <(echo -n " ") jq.txt)` in my shell does this without
letting any program other than jq attempt to parse any UTF-8 sequences
(keeping vim and friends from trying to "help").
The extra space on the front causes it to print properly.  In fact, any odd
number of bytes on the front of the file causes it to print properly.
The implication here is that there's a bug in jq's UTF-8 parser.

**Comment by pkoppstein** [comment] 2017-01-23 21:12
@wtlangford - Yes, I can confirm that the extra space makes a difference on my machine too.  Thanks.

**Comment by wtlangford** [comment] 2017-01-23 23:51
Reopening this because it seems the issue is related to a UTF-8 byte sequence spanning across byte offset `0xffff`, meaning this is likely a buffer-size problem.

**Comment by wtlangford** [comment] 2017-01-24 02:28
Further investigation yields that the issue doesn't occur when reading json inputs, but in parsing jq programs themselves, which means this bug comes from flex/bison.  This may be significantly harder to resolve.

**Comment by nicowilliams** [comment] 2017-01-24 03:57
Ah, sorry for closing this too soon.

**Comment by nicowilliams** [comment] 2017-01-24 22:40
Hmmm, `jq -n '"საერთაშორისო"'` works (this string is just a copy-paste from https://www.w3.org/2001/06/utf-8-test/UTF-8-demo.html).

**Comment by nicowilliams** [comment] 2017-01-24 23:25
Oh, I see.  This really is weird!

**Comment by wtlangford** [comment] 2017-01-24 23:50
Good news! This is not a flex bug.  It's in `jv_load_file`.  I'm working on a fix for it.

**Comment by nicowilliams** [comment] 2017-01-25 00:09
@wtlangford Nice!

**Comment by pkoppstein** [comment] 2017-01-25 04:08
@nicowilliams, @wtlangford - This is such a weird bug that it would be great to have it fixed in the next official release of jq, but otherwise, there is in my opinion nothing else of which I'm aware that warrants further delay in an official release.  (Generally, the anticipated changes either address problems that have satisfactory, or at least reasonably satisfactory, workarounds, or else carry some kind of risk, if only with respect to backwards-compatibility.)

jq 1.5 was released in Aug 2015, and there have been several requests (pleas?) for another.  Many bug reports (most recently #1316) are about bugs that have been fixed on master. 

The March 2016 version (0b8218515eabf1a967eba0dbcc7a0e5ae031a509) has proven to be very reliable (except for #1311), and it's a pity it wasn't elevated to official release status long ago.  I know there are some significant outstanding issues that it would be nice to resolve, but I'd like to request that priority be given to having a release ASAP after #1311 has been resolved.  

Thanks!

**Closed** 2017-01-28 02:45 UTC
Labels: bug
