### ISSUE TITLE
Shell calls

### ISSUE THREAD

**Issue by adrianmay** [stedolan/jq#1265] opened 2016-10-27 11:54 UTC
Hi,

I 'd like to write something like: 

<pre>
echo '["Pinky", "Perky"]' | jq '[ .[] | `tr "[a-z]" "[A-Z]"` ]'
</pre>

to get 

<pre>
[
   "PINKY",
   "PERKY"
]
</pre>

Is that likely or silly? 

It would be better still if the parameter could be stuffed into the middle of the shell command, perhaps by building it as a string and piping that to a shell filter.

I'm aware of the @sh filter, but the idea is to shell-munge something deep inside a json structure. Perhaps, given the opposite of @sh you could capture the output from the shell command into an array.

**Comment by pkoppstein** [comment] 2016-10-27 20:06
Unfortunately jq has no "shell escape" mechanism and so, if using jq at all, a good rule of thumb is to use jq's fairly extensive repertoire of filters as much as possible.  To use them effectively may require learning about programming in jq, but that is quite easy.  

jq's ability to read data from multiple sources may also come in handy -- see especially the documentation on the --arg, --argfile, and --slurpfile options, and on "import RelativePathString as $NAME".

You might also like to consider using jq as an embedded processor within Python, Ruby, or PHP.  See https://github.com/stedolan/jq/wiki/FAQ#language-bindings

**Comment by nicowilliams** [comment] 2017-01-23 22:04
We have serveral RFEs for this sort of thing.  Some day...

**Comment by bortzmeyer** [comment] 2017-03-23 15:45
Seems a duplicate of #1101

**Comment by nicowilliams** [comment] 2017-03-24 03:44
Indeed.

**Closed** 2017-03-24 03:44 UTC
Labels: dup
