### ISSUE TITLE
validation failure: not reporting incomplete JSON as invalid

### ISSUE THREAD

**Issue by stinney** [stedolan/jq#1305] opened 2017-01-08 19:56 UTC
The json input file "}" produces an error; the input "{" does not.

**Comment by pkoppstein** [comment] 2017-01-08 22:23
1. When reporting a problem, please indicate the jq version number and some details about the environment.  A short transcript illustrating the problem is usually helpful.

2. The problem you describe may already have been resolved.  Consider:
```
$ echo '}' | jq1.3 .
parse error: Unmatched '}' at line 1, column 1

$ echo '{' | jq1.3 .
parse error: Unfinished JSON term

$ /usr/local/bin/jq -V
jq-1.4

$ echo '{' | /usr/local/bin/jq .
parse error: Unfinished JSON term

$ echo '}' | /usr/local/bin/jq .
parse error: Unmatched '}' at line 1, column 1
```

**Comment by yurivict** [comment] 2017-01-10 06:17
1.5 has this problem.

**Comment by wtlangford** [comment] 2017-02-08 21:58
1.5 has this problem, but this is fixed on master.
```
$ ./jq -V
jq-1.5rc2-174-g597c1f6 # read as: commit hash 597c1f6, which is 174 commits ahead of tag jq-1.5rc2.
$ echo '{' | ./jq .
parse error: Unfinished JSON term at EOF at line 2, column 0
$ echo '}' | ./jq .
parse error: Unmatched '}' at line 1, column 1
$ echo -n '}' | ./jq .
parse error: Unmatched '}' at line 1, column 1
$ echo -n '{' | ./jq .
parse error: Unfinished JSON term at EOF at line 1, column 1
```

**Closed by wtlangford** 2017-02-08 21:58 UTC
Labels: bug, fixed in master

**Comment by yurivict** [comment] 2017-02-08 22:03
Is there an ETA of the next release?
