### ISSUE TITLE
Do not require parens for non-constant-string map literal keys

### ISSUE THREAD

**Issue by dtolnay** [stedolan/jq#947] opened 2015-09-14 17:54 UTC
Current: `{($a[0]): $a[1]}`
Desired: `{$a[0]: $a[1]}`

This requires fixing some precedence issues. For example in `{"a":"b","c","d":"e"}` there is an ambiguity between `{"a":("b","c"),"d":"e"}`, `{"a":"b",("c","d"):"e"}`, and `{"a":"b","c":(.["c"]),"d":"e"}`. The current behavior is the third, so we want to keep that.

**Comment by nicowilliams** [comment] 2015-09-14 19:18
Right, the problem is the commas.  What if we do this:

    diff --git a/src/parser.y b/src/parser.y
    index d57e5c8..75e3208 100644
    --- a/src/parser.y
    +++ b/src/parser.y
    @@ -900,6 +900,9 @@ IDENT ':' ExpD {
       $$ = gen_dictpair(gen_const(jv_copy($1)),
                         gen_index(gen_noop(), gen_const($1)));
       }
    +| Term ':' ExpD {
    +  $$ = gen_dictpair($1, $3);
    +  }
     | '(' Exp ')' ':' ExpD {
       $$ = gen_dictpair($2, $5);
       }

Now we're down to 4 shift/reduce conflicts.

**Comment by nicowilliams** [comment] 2015-09-14 19:20
We could also make the `MkDictPair`'s error be more useful.

**Comment by dtolnay** [comment] 2015-09-14 20:31
@nicowilliams that works and the shift/reduce conflicts are easy to fix, but it still rules out unambiguous cases that one would reasonably expect to work, for example `{"a"+"b":0}`. I will think about a more flexible solution this week.

**Comment by nicowilliams** [comment] 2015-09-14 21:09
There's also `{(def foo: .; foo):.}`.  I don't mind requiring parens for that sort of thing.  That is, the two tokens that cause trouble here are `:` and `,`, and `:` we can require parens for.  As for ','...  I'm not sure the fix won't also be surprising.

Can we just improve the error message?  That might be good enough.

**Comment by dtolnay** [comment] 2015-09-16 16:55
There is another ambiguity with /0 functions:

    jq -n '3 | {type: 0}'

Is this `{"type": 0}` or `{"number": 0}`? To be consistent with 1.5, it needs to be `{"type": 0}`.

This one makes me concerned that this change will cause more confusion than just fixing the error message. PR #950.

**Comment by pkoppstein** [comment] 2015-09-16 17:29
@dtolnay - Yes, this is the poster-child for "wontfix".

**Comment by nicowilliams** [comment] 2015-09-16 17:42
I agree.  We could define a subset of `Exp` or `Term` that has no such ambiguities, but I think not requiring parens for some key expressions would only confuse users more.  Better just improve the error message.

**Closed** 2015-09-16 17:55 UTC
Labels: usability, wontfix
