### ISSUE TITLE
jq unable to deal 64 bit number

### ISSUE THREAD

**Issue by jackiesteed** [stedolan/jq#1387] opened 2017-04-11 09:32 UTC
echo  '{"number":288230376151711744}' | jq '.number'
the output is 288230376151711740

**Comment by wtlangford** [comment] 2017-04-11 12:50
This is [often](https://github.com/stedolan/jq/issues/1357) [reported](https://github.com/stedolan/jq/issues/1363). (see also https://github.com/stedolan/jq/issues/545, https://github.com/stedolan/jq/issues/529, and https://github.com/stedolan/jq/issues/178)

The summary here is that it's not a bug. Internally, we use IEEE754 doubles, and those can't perfectly represent all integers, especially not all large ones.  We have a feature we're working on (https://github.com/stedolan/jq/pull/1327) that will somewhat improve this behavior.

Closing as a duplicate.

**Closed by wtlangford** 2017-04-11 12:50 UTC
