### ISSUE TITLE
incorrect handling of ./ in search path

### ISSUE THREAD

**Issue by dtolnay** [stedolan/jq#817] opened 2015-06-19 03:44 UTC
Currently on master:

    jq$ ./jq -L tests/modules -n 'import "test_bind_order" as check; check::check'
    true
    jq$ ./jq -L ./tests/modules -n 'import "test_bind_order" as check; check::check'
    jq: error: module not found: test_bind_order0

    jq: 1 compile error

**Comment by nicowilliams** [comment] 2015-08-11 04:47
This is a bug, yes.  The root cause is this: we try to support searching paths relative to the module doing the inclusion, but we also include the global locations in the search path, and so we have confusion: is a relative path relative to the jq program origin or to the including module?

The fix is obviously to make absolute paths out of relative paths sooner.  With care to properly detect relative vs. absolute paths on Windows (probably using PathIsRelative()).

**Comment by nicowilliams** [comment] 2015-08-11 04:50
Actually, in `main()` we can just apply `jq_realpath()` to make `-L` arguments absolute.

**Comment by nicowilliams** [comment] 2015-08-11 04:58
We still need to properly detect relative paths in the linker, so both need fixing.

**Comment by nicowilliams** [comment] 2015-08-11 04:59
This confusion rates as needing to be fixed in 1.5, IMO.

**Closed** 2015-08-13 16:11 UTC
Labels: bug
