### ISSUE TITLE
Missing color option - label color fixed

### ISSUE THREAD

**Issue by JosefLitos** [stedolan/jq#2392] opened 2021-12-30 11:10 UTC
There are specified all colors in JQ_COLORS except the labels of values, those' color cannot be changed. I have a colorscheme and I wanted to adapt ranger previews to it, so I would like to alter this color too.

**Comment by itchyny** [comment] 2021-12-30 11:22
Duplicate of #1739.

**Closed** 2021-12-31 15:28 UTC
