### ISSUE TITLE
'.' identity changes non-ascii data in raw mode

### ISSUE THREAD

**Issue by clintoncampbell** [stedolan/jq#1466] opened 2017-08-24 21:51 UTC
While creating a pipeline to extract content from a file that is typically base64 encoded in a JSON wrapper, e.g., `{ "filename":"foo", ..., "content":"aGVsbG8sIHdvcmxkCg=="}`, but may also appear as raw data, I discovered that jq does not respect the '.' identity when handling raw binary data. 

The issue can be replicated by running: `jq -Rr '.' < in.bin > out.bin`. The change should be immediately visible in that the length out the output will have grown. With the input of a simple gzipped archive, my data grew from 143 to 232 bytes. 

This growth leads me to believe that the issue has something to do with character encoding. I have experimented with various other options like `-a` without any change in results. For reference, the original command I was attempting appears as follows: `jq -Rr --stream '. | (fromjson | tostream | select(.[0][0] == "content") | "B64"+.[1])? // "RAW"+tostring'`.

**Comment by wtlangford** [comment] 2017-08-24 22:05
The issue is that raw data is not necessarily valid json. Raw modes assume
the input/output to be unquoted json strings, but otherwise valid.
This means that any sequence of bytes that is not valid utf8 will end up
mangled as jq parses the utf8 string. (Additionally, any ascii control
characters most be escaped, as per the json spec).

This is a long way of saying that this is not a behavior jq is intended
for, as jq operates on json values only.

You'll need to ensure the data is either properly escaped for utf8 or
base-64 encoded before processing it with jq.

**Comment by clintoncampbell** [comment] 2017-08-24 22:18
Well, bummer. I was pretty excited about the simplicity of this solution in
that I could catch the error and pipe my input through unchanged if json
wasn't parsed correctly. Perhaps there is a feature request in here?

It may also be worth further clarification in the manual to avoid confusion
around this.
Thanks

**Comment by wtlangford** [comment] 2017-08-24 22:44
Hm, there's not really much room for a feature request, unfortunately. The
problem is that jq isn't able to process non-utf8 strings, and raw binary
data is notably often not utf8.

Any thoughts on what particular language you think would best improve the
documentation? If so, feel free to make a PR with the doc improvement, and
I'll try to get it merged soon! (one day I'll have free time again, I'm
sure of it...)

(Side note: I might complain at whoever's providing  data in mixed formats
and tell them to be more consistent, were I in your shoes.)

**Comment by nicowilliams** [comment] 2017-11-28 18:18
We don't have support for raw _binary_ data yet.

**Closed** 2017-11-28 18:18 UTC
Labels: dup, feature request, support
