### ISSUE TITLE
manpage examples have too large vspace

### ISSUE THREAD

**Issue by else** [stedolan/jq#86] opened 2013-02-20 21:33 UTC
The examples given in the manpage are surrounded by large blocks of whitespace. This is caused by a bug in ronn (which is unfortunately currently unmaintained): https://github.com/rtomayko/ronn/issues/63

**Comment by dtolnay** [comment] 2015-08-25 05:14
Closing because this is not a bug in jq, and the default man pager works around this anyway.

**Closed by dtolnay** 2015-08-25 05:14 UTC
Labels: docs, external bug
