### ISSUE TITLE
walk example doesn't work

### ISSUE THREAD

**Issue by emayssat-ms** [stedolan/jq#1245] opened 2016-10-03 01:01 UTC
On this page
https://stedolan.github.io/jq/manual/
going to the walk(f) section.
Click on Run

returns in the playground 

jq: error: walk/1 is not defined at <top-level>, line 1:
walk(if type == "array" then sort else . end)
jq: 1 compile error
exit status 3

**Comment by pkoppstein** [comment] 2016-10-03 02:56
Currently the "playground" uses jq 1.5 but `walk/1` was added after the release of jq 1.5.

`walk/1` is just a jq-defined function, the definition of which can easily be found by googling for:

    "def walk" jq

**Comment by dedeibel** [comment] 2017-01-13 08:26
Please add "since version" information to new functions in the manual.

**Comment by adamchainz** [comment] 2017-02-22 15:39
Dupe of #963 which has the code ready to copy/paste.

+1 on "since version" annotations in manual.

**Comment by nicowilliams** [comment] 2017-02-22 15:58
@dedeibel @adamchainz The online manual links to the each version's manual.  That's about as much as we're likely to do to record version differences, and it's probably enough anyways, since you can always refer to the appropriate jq version's manual.

**Closed by nicowilliams** 2017-02-22 15:58 UTC

**Comment by dedeibel** [comment] 2017-02-22 16:07
Well, google led me to the docs. There I read about the feature. I was confused why it didn't work for me, tried this and that ... costed quite some time.

I didn't even now I had to look out of a version specific manual. The "since version" or something similar would have emphasized this.

Now I know about the different version manuals, sure, but nowadays I doubt the use case of visiting a website and looking at every detail of it. You just google things.

**Comment by adamchainz** [comment] 2017-02-22 16:15
@nicowilliams I did search around the page, and understood the text under the header "For released versions, see jq 1.5, jq 1.4 or jq 1.3." as meaning "This documentation is for the released versions 1.5, 1.4, or 1.3". It's only when reading your message just now I understood the actual meaning. I think this could be rephrased a bit.

**Comment by nicowilliams** [comment] 2017-02-22 16:56
@adamchainz Suggestions?

Maybe we should change the heading to have "development" in bold and/or red?

**Comment by adamchainz** [comment] 2017-02-22 17:01
This is a nice banner: https://docs.djangoproject.com/en/dev/ref/models/instances/

**Comment by nicowilliams** [comment] 2017-02-22 17:35
@adamchainz  Interesting.  I almost didn't see it.  Those tend to be "our site uses cookies banners", which I'm just completely blind to.  If you'd not said the word "banner", I'd not have seen it.  I suppose we could leave the title (with bolded, red "development") and _add_ a banner.
