### ISSUE TITLE
Module system is a mess

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#672] opened 2015-01-19 22:16 UTC
@joelpurra @pkoppstein @wtlangford 

It's been a few weeks since I've given this any thought.  Here's an attempt to look at the whole jq module system from a fresh perspective.

jq has no build artifacts at this time, no `.jqc` files.  This means that .jq files (sources) cannot contain "absolute" references to dependencies: relative paths are OK, absolute paths are not OK, minimum version numbers are OK, exact version numbers (and/or commit hashes, etcetera) are not.

Absolute locators/bindings have to be in an external location, in a `.jqc` or in a `.json` or some such file.  Or else we must do without absolute locators/bindings, using dependent- and/or universe-relative locators only, leaving absolute binding to an external link-editor of sorts (a/the packaging system) that can use symlinks to resolve relative bindings.

In general absolute bindings at run-time is the best answer for semantic reasons (absolute bindings mean repeatable results) and for performance reasons: the work of link-editing can be done at build- (or, libtool-like, at intstall-) time.  We don't have this luxury at this time, but we shouldn't want to close the door on a future `.jqc` world either (nor, in such a future, would we want to force all jq programs and modules to be compiled).

For user-friendliness it really helps for a language like jq (which has not build step) to support running "in place", meaning: without having to `make install` then run from the install location.

On thing that becomes obvious is that we shouldn't really have a "path" (relative or otherwise) in `import` directives in `.jq` "source" files: it's a locator, even if relative, when all we need is a "name" -- an identifier.  Ideally we'd have:

    import as foo {uri: "...", <perhaps other metadata>};

If you want to use whatever that module is, your pkg system has to fetch and install it (if it isn't already installed) relative to the install location of your dependent so you can run it.

But then we absolutely need a separate file, built by the pkg mgr (really, now functioning as a link-editor) in which to store resolved dependency information that *jq* will read.  And then we need a build step, which I think we don't and shouldn't want to _require_.

I think that's a fair synthesis of the problem we're facing.  Would you agree?

So now what?

The problem that arises is that we need to have two somewhat contradictory options work with the same source code for the dependent:

 - external file with absolute locators
 - run in-place must work

Which means we need to distinguish at run-time (since that's all we have right now) whether a dependency is intended to be run in-place or otherwise, and we need the `import` directive to provide enough information for both: the external link-edit/pkg mgr case, and the run in-place case.

The only tool we have for squaring this circle without requiring additional steps to build/install additional metadata files, is installing all dependencies local (relative) to their dependents, possibly with symlinks where available.  But there's no reason that we couldn't support the use of additional metadata files as an option.

It could be OK to have `import` directives which, as-written, only support the external link-edit/pkg mgr case:

    # Locator for "foobar" must be in .jqc file (or .json?)
    # (look ma'!  no path here!)
    import as foo {name:"foobar", <other metadata>};

But it should also be OK to have `import` directives with relative path locators for running in-place without necessarily having to run an external link-edit/pkg mgr tool:

    # Search [<dependent's $ORIGIN>, <universe $ORIGIN>] for
    # "some/path/to/mod/src/mod.jq", "some/path/to/mod/mod.jq":
    import some/path/to/mod as sym {dir:["src", null]};
    
with metadata options for various location algorithms as desired.

Relatedly, what would it take to actually add a build step to jq, and a `.jqc` file format?  Ideally we'd write bytecode (to make run-time loading fast), but because of the way jq does link-editing now we'd either have to re-write a lot of `compile.c`, `bytecode.c`, and `linker.c`, or we'd have to instead serialize the intermediate representation of jq programs ("blocks").  (Also, bytecode generation depends on knowing whether a function being called is C-coded or not.  Delaying this to run-time loading and linking time would require bytecode fixup anyways...)  Obviously, for a first version we could go for the latter.  But still, it'd be a fair amount of work.  For now all we need is the jq source and the fully-resolved dependency locators, something like: `["jqc",1.5,{<dependency locators>},"<source code>"]`.  A future version might look like `["jqc",1.6,<dependency locators>, <binary serialization of block representation of source>` (i.e., no longer JSON).  The file magic would be: it starts with `["jqc",`.

An external tool could produce `["jqc",1.5,{<dependency locators>, "<source code>"]` today, with no new help from jq (no `--compile` option needed).  I'm liking the `modulemeta` builtin as a helper for such an external tool: it can use it to extract the import directives, add any additional external pkg metadata, resolve universal identifiers/locators for the dependencies, install them, resolve local filesystem locators for them, and write the `.jqc` files.

This way we could support all the use-cases that we want:

 - run in-place
 - run with dependencies installed in `$HOME/.jq/<universe-name>`
 - run with dependencies installed in `$HOME/.jq/default/`
 - run with dependencies installed in `/usr/lib/jq/...` (perhaps with Nix-style `<hash>-<name>` directories or symlinks to them)
 - run with dependencies installed local to each dependent (except for and/or including programs, which might be in a bindir, but still, a `$ORIGIN/../lib/...`-style path should work).

Of course, one could write programs/modules that only work with a pkg mgr (because no relative path is given).  That might be seen as unfriendly to users, but I think it's fine: if you're really writing production code in jq (as I have) then you'll want a build/install step anyways.  Even if you're just playing, an "install dependencies" step seems reasonable if you're going to use external dependencies you didn't write.

**Comment by nicowilliams** [comment] 2015-01-19 22:17
I'm quite tempted to go with something real simple, with the "src" (or "jq") and "packages" directories that caused such controversy being things specified to be inserted (if at all) in `import` directive metadata.

**Comment by pkoppstein** [comment] 2015-01-19 22:51
@nicowilliams wrote:
> Module system is a mess .... I'm quite tempted to go with something real simple

Excellent!!!!

I think that @joelpurra is correct that it should be *easy* for the end-user to be able to specify a project-specific directory, but it also seems to me that things started getting complicated because the idea of a "package manager" started to obliterate the idea of jq itself having a very simple *module* system. 

Anyway, I'd like to suggest a useful criterion for simplicity here: that it should be possible to use any of the "jq-registered modules" (once they have been installed) without any configuration file, and without any (or at least, with as few as possible) command-line options.

**Comment by nicowilliams** [comment] 2015-01-19 23:31
Well, I'm still not sure what the "simple" thing should be.

One option is to specify the pkg conventions ("src", "packages" directories) at the top-level program, in a `module` directive, in the `import` directive, or bake-in a default but allow overriding it.  I'm not sure.

What I am sure about is that a module system without a compiled file system *is* the problem, but there's no chance to add that in before 1.5, but excluding a module system in 1.5 would be lame.  This means that 1.5's module system can't be ideal.  1.6 can fix it by adding a compilation step for those who prefer the clean system.

**Comment by pkoppstein** [comment] 2015-01-20 00:04
@nicowilliams lamented:
> I'm still not sure what the "simple" thing should be.

There's something to be said for enunciating the principles of interest rather than attempting to ascertain the quintessence of simplicity itself.

From memory, the only thing that really needs to be baked-in is that when vanilla jq sees "import Shazam;" (or equivalent) outside a module file, it will attempt to load  ~/.jq/packages/Shazam/Shazam.jq  (or equivalent (*)). 

(*) If jqnpm really needs to be able to find main.jq and cannot create a symbolic link as part of the installation process, then I can live with ~/.jq/packages/Shazam/main.jq.

**Comment by nicowilliams** [comment] 2015-01-20 05:32
On Monday, January 19, 2015, pkoppstein <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> @nicowilliams <https://github.com/nicowilliams> lamented:
>
> I'm still not sure what the "simple" thing should be.
>
> There's something to be said for enunciating the principles of interest
> rather than attempting to ascertain the quintessence of simplicity itself.
>

Yes, that's the idea.  I was just about to write that "oddly enough I
haven't yet reached a different conclusion, even though..."  And I think I
have it, but I need to flesh it out more first.


> From memory, the only thing that really needs to be baked-in is that when
> vanilla jq sees "import Shazam;" (or equivalent) outside a module file, it
> will attempt to load ~/.jq/packages/Shazam/Shazam.jq (or equivalent (*)).
>
(*) If jqnpm really needs to be able to find main.jq and cannot create a
> symbolic link as part of the installation process, then I can live with
> ~/.jq/packages/Shazam/main.jq.
>

Both, or neither, if the idea I'm going to play with works out.

Remind me: why "packages"?  What would be found in `~/.jq` besides that one
directory?  If the answer is "nothing" then why add that one directory?

**Comment by pkoppstein** [comment] 2015-01-20 06:11
@nicowilliams asked:
> Remind me: why "packages"?

@joelpurra has been using the name "packages" and I agree with him that such a directory is very important, and in certain respects, essential. I won't try to recapitulate his rationale, and indeed I'm not sure I recollect all the reasons why I came to the conclusion that it's essential, but the crux of the matter (from my perspective) is the ability to accommodate the needs of a user who may want to be able to use (a) different versions of jq; (b) different versions of different package managers; (c) different "channels" (my terminology for different "package metadata repositories", i.e. sources of metadata information about packages). 

More generally, it makes things more flexible, and adheres to the principle about keeping like-things together.  Maybe someone will want ~/.jq/jqrc or ~/.jq/jqnpm.json, etc etc.

Of course all this makes even more sense if there is some way to get jq to look in a directory other than (or before) ~/.jq/ -- e.g. via -L and/or -P.   The details or such mechanisms, however, can be worked out later.

**Comment by nicowilliams** [comment] 2015-01-20 06:28
Right, I call what you call "channel" a "universe", but still, why "packages", why not just `$HOME/.jq/<universe-name>/...`?

**Comment by nicowilliams** [comment] 2015-01-20 06:30
And also, what was the answer to my question?  What would be under `$HOME/.jq/` if not just one or more universes?  If it's just one directory ("packages") containing multiple universes, then there's no need for that one directory.  If you want to add in unmanaged modules (e.g., `$HOME/.jq/foo/stuff/...` being unmanaged and `$HOME/.jq/packages/foo/...` being managed) then I'd ask why.

**Comment by nicowilliams** [comment] 2015-01-20 06:34
For (a), (b), and (c) the answer is the same: put things in `$HOME/.jq/<universe-name>/` and let jq know to search in the appropriate universe (with `-L` or with symlinks; for jq programs in bindirs symlinks don't help, but then, "packages" doesn't either).  We may need an option for "universe name" that is separate from "library path", but that's a separate matter.  One thing at a time.

**Comment by nicowilliams** [comment] 2015-01-20 06:37
Note that `$HOME/.jq/jqrc` doesn't conflict with anything other than a universe named "jqrc", and if we make universe names be identifiers then `$HOME/.jq/jq.rc` and `$HOME/.jq/jqnpm.json` wouldn't conflict with any universe names ever.  Ditto `$HOME/.jq/.whatever`.

So, what else might go in `$HOME/.jq/` that would conflict with a universe name?

**Comment by nicowilliams** [comment] 2015-01-20 06:39
And, if we really need such a directory, is there any reason it couldn't be a string of one ASCII character?

On Windows long paths *really* hurt.

**Comment by nicowilliams** [comment] 2015-01-20 06:54
Here's a strawman proposal that is *very* simple:

 - all jq programs in bindirs must be generated and will consist of one directive to specify the universe of the program (as an absolute path or as a path relative to the program's bindir with `..` traversal permitted), one `import` directive, and a trivial top-level expression: `main` (from the imported module)
 - all imports from modules will be searched for relative to the dependent's dirname, then (failing the first) relative to the top-level program's universe.

For programs given on the command-line or not being generated as above, the `-L` argument will provide the path to the universe.

I think this takes care of everything *except* the run-in-place case, which I would be willing to discard (must install to use).

Alright, have at it, knock it down.

**Comment by pkoppstein** [comment] 2015-01-20 07:04
@nicowilliams asked:
> why not just $HOME/.jq/<universe-name>/.

Because of the zero-configuration goal (or if you prefer, the zero-configuration-after-installation goal).
Using your terminology, there needs to be a default "universe".  Call it "packages", "universe", "all", or whatever, but it needs to be there (from the perspective of making things simple for the end-user).

I agree that if there were no need to be able to switch between universes conveniently, then there'd be no need for a default "universe" name.  That is, as you say, "~/jq/Shazam/Shazam.jq"  could easily co-exist with configuration files, etc. 

Thus it would be reasonable to say that it's really the need to switch conveniently between different universes that's the reason for having a subdirectory of ~/.jq that reflects the name of the universe.

However, from my perspective, the MOST important thing is that jq have a default directory in which to try to find installed module files. All things considered, ~/.jq/packages seems to make the most sense (not least because it meets or conforms with @joelpurra's requirements, at least as I understand them), but variants such as ~/.jq/universes, ~/.jqpm/modules, etc., would be fine.

**Comment by pkoppstein** [comment] 2015-01-20 07:10
@nicowilliams wrote:
> On Windows long paths really hurt.

A single-character name (e.g. "0" -- as in "in the beginning"?) for the default package "universe" would be fine by me.

**Comment by pkoppstein** [comment] 2015-01-20 07:19
@nicowilliams wrote:
> For (a), (b), and (c) the answer is the same: put things in $HOME/.jq/<universe-name>/ and let jq know to search in the appropriate universe

The main thing I'm asking for is that there be a default "<universe-name>".  Call it U, u, 0, jq, any, all, modules, packages, channels, v1.5, ..... whatever takes your fancy!

**Comment by nicowilliams** [comment] 2015-01-20 16:40
On Mon, Jan 19, 2015 at 11:04:05PM -0800, pkoppstein wrote:
>  @nicowilliams asked:
> > why not just $HOME/.jq/<universe-name>/.
> 
> Because of the zero-configuration goal (or if you prefer, the zero-configuration-after-installation goal).
> Using your terminology, there needs to be a default "universe".  Call it "packages", "universe", "all", or whatever, but it needs to be there (from the perspective of making things simple for the end-user).

In my strawman there is zero configuration and you get universes by
convention.  (Or not; maybe you want Nix-style packaging, and you then
get no universes at all.)

> I agree that if there were no need to be able to switch between universes conveniently, then there'd be no need for a default "universe" name.  That is, as you say, "~/jq/Shazam/Shazam.jq"  could easily co-exist with configuration files, etc. 
> 
> Thus it would be reasonable to say that it's really the need to switch conveniently between different universes that's the reason for having a subdirectory of ~/.jq that reflects the name of the universe.
> 
> However, from my perspective, the MOST important thing is that jq have a default directory in which to try to find installed module files. All things considered, ~/.jq/packages seems to make the most sense (not least because it meets or conforms with @joelpurra's requirements, at least as I understand them), but variants such as ~/.jq/universes, ~/.jqpm/modules, etc., would be fine. 

In my strawman, jq programs in system bindirs look like this:

    #!/usr/bin/jq
    import foo/bar/baz {search:"/usr/lib/jq/BLAH"} as main;
    main::main

or Nix-style:

    #!/usr/bin/jq
    # Nix-style hash-name
    import "a1b2c3d4-foo/a5b1c3d2-bar/a9b1c7d6-baz" as main {search:"/usr/lib/jq/BLAH"};
    main::main

jq programs in user bindirs would look the same but with a path that looks like `"~/.jq/..."`, of course.

Command-line runs look like this:

    $ # Look in $HOME/.jq, but we add "BLAH" here
    $ jq 'import BLAH/foo/bar/baz as null; stuff'

or

    $ # jq should be smart enough to append -L to search
    $ # list elements when they are not absolute, and don't
    $ # start with $ORIGIN/ or ~/
    $ jq -L BLAH 'import foo/bar/baz as null; stuff'

or

    $ # Of course, -L knows absolute paths..
    $ jq -L $HOME/.jq/BLAH 'import foo/bar/baz as null; stuff'

and so on.

You get universes by convention IF you want them.  If you don't want them, you don't have to have them.

If you want a Nix-style pkg store with every pkg named by a hash, you can get that too.

All dependencies of modules are resolved by symlinks.

In order to avoid dependning on symlinks where they are not supported I'd be happy to let jq read a `.json` file to serve the same function as symlinks: list the absolute locations of dependencies.  This is something @joelpurra wanted, and I see the point now.

    $HOME/.jq/pkgs.json      <-- list installed modules and their locations
                                 and other state
    $HOME/.jq/DIR/dir.jq     <-- actual module
    $HOME/.jq/DIR/deps.json  <-- absolute dependency locators
    
    or
    
    $HOME/.jq/DIR/dep        <-- symlink to some dependency
    $HOME/.jq/DIR/dep/dep.jq <-- the actual dependency
    
    and
    
    $HOME/.jq/.tmp/pkgs.json <-- list in-progress installs, use as lock file
    $HOME/.jq/.tmp/DIR/...   <-- git/Mercurial/whatever clones, untarred
                                 tarballs, ..., where the pkg mgr will
                                 then install pkgs from.
    
                                 (Of course this could just be in /tmp,
                                 and tempdirs to rename into place
                                 should be made in the same parent
                                 directory as the directory will have
                                 after renaming into place.  But one
                                 might want a directory under $HOME/.jq/
                                 in which to place git/hg/...
                                 workspaces to instal from.)

The install-a-module process would work as follows:

 - the pkg mgr reads a .json (or module metadata from .jq files; whatever pleases the pkg mgr author) to extract metadata about a module's dependencies

 - the pkg mgr downloads/clones the dependencies into temp working directories

 - the pkg mgr "builds" (if necessary) the downloaded/cloned dependencies

 - the pkg mgr installs the built dependencies into place in the appropriate location under `$HOME/.jq/`

If the pkg mgr wants to deal in universes, then it will add a universe name prefix to the installed pkgs' path.

What if you mix multiple pkg mgrs?  Well, we'll see.

What if you mix multiple jq versions?  Well, then maybe you'll want universes with jq version numbers in them.  But Nix-style pkg stores will automatically take care of jq version dependence.

If we go with Nix-style pkg stores then we'll need top-level universes populated with symlinks (or .json files) to help jq find modules when running from the command-line or from jq files not in bindirs (i.e., not installed).

This has the benefit that it's trivial to implement and document in jq.

A Nix-style pkg store naturally won't conflict with anything else.  A multiple-universe scheme can arise by convention.

What's wrong with this?

**Comment by nicowilliams** [comment] 2015-01-20 16:41
On Mon, Jan 19, 2015 at 11:19:59PM -0800, pkoppstein wrote:
> @nicowilliams wrote:
> > For (a), (b), and (c) the answer is the same: put things in $HOME/.jq/<universe-name>/ and let jq know to search in the appropriate universe
> 
> The main thing I'm asking for is that there be a default "<universe-name>".  Call it U, u, 0, jq, any, all, modules, packages, channels, v1.5, ..... whatever takes your fancy!

Sure, that's fair, and I'll do that.

**Comment by joelpurra** [comment] 2015-01-20 20:18
I have no idea why this discussion has been restarted; I've been offline and haven't caught up.

I have a POC in #673. Try it out. It uses `$PACKAGEROOT/` (similar to `$ORIGIN/`).

**Comment by pkoppstein** [comment] 2015-01-20 22:25
@joelpurra wrote:
> I have no idea why this discussion has been restarted

As far as I can tell, @nicowilliams came to this conclusion himself. Until he created #672, I had been silent on the topic of modules and packages since December.

But I do like the jqnpm logo!

> I have a POC ...

"POC".  Hmmm.  Yes, that gets to the heart of the matter, as it seems to me you tend to assume that your audience has the same mindset as you do.

Of course one always has to make some assumptions about one's
audience, but my hope for jq and associated tools is that they should
be easy to use for someone who does not know much about command-line
tools.  For example, I have in mind someone who is proficient at using
Word, Excel and R Studio, who knows a little about JSON, but for whom typing 
"echo hello" at a command-line prompt is a stretch.

Anyway, here is some food for thought:

i) When I installed jqnpm some time ago, I created a symlink (from
~/bin to ~/github/jqnpm/src/jqnpm).  At one point, that worked.  But now:
```
$ jqnpm -h
jqnpm -h
~/bin/jqnpm: line 10: ~/bin/shared/functions/debug.sh: No such file or directory
```
Yes, I know what the problem is, but there are at least two signficant points here:

  a) the instruction to "export PATH=....$PWD/jqnmp/src" is fine for the cognoscenti, but not for my target audience, as the change would only be effective in that one shell and its children.

  b) The jqnpm script ought to allow it to be referenced as a symlink.

ii) The installation instructions for jq-stress are:

"Install the package in your jq project/package directory with jqnpm:"

This is ambiguous between:

* "The following command will install the package in your jq project/package directory"; and

* "After running the appropriate cd command to make your project/package directory the present working directory, ..."

Also, it's not clear what "your project/package directory" means.  Is
it the package subdirectory of my project, or is it my choice as to
whether a project or package directory is used?  What if I don't have
a "project directory"?

Anyway, the install command gives a rather scary warning:
```
$ cd jq/test
$ jqnpm install joelpurra/jq-stress

jqnpm: [WARN]	folder (package) name does not start with 'jq-': 'test'
```
Did I do something wrong? Do I have to start again?  How would I go
about doing that?  What should I do differently? What if I don't do anything?

In short, my users have panicked.

iii) OK, they have calmed down a bit.  With a bit of encouragement, we have some success:
```
~/github/jqnpm/src/jqnpm execute -n 'import "joelpurra/jq-stress" as Stress; "Hello" | Stress::remove("e")'
"Hllo"
```
But a few seconds later ....
```
$ cd 
$ ~/github/jqnpm/src/jqnpm execute -n 'import "joelpurra/jq-stress" as Stress; "Hello" | Stress::remove("e")'
jq: error: module not found: joelpurra/jq-stress
```
Now what?  Should I have named the package "jq-joelpurra/jq-stress?"
Where was that package installed?  Can I use it outside the confines of the project directory? ....


iv) The "Usage" section of the jq-stress documentation is long on
examples, but raises more questions than it answers.  Does "replace"
replace once or multiple times?  Why is isEmpty needed? Is it faster
than using length?

(By the way, I would argue that it would be better to reserve the prefix "is" for predicates. Yes, I know about Microsoft.  ifNull would be OK; or if you want to follow ISO/ANSI SQL standards, COALESCE would be a good place to start.)

**Comment by joelpurra** [comment] 2015-01-21 03:05
> But I do like the jqnpm logo!

Yay!

> I have a POC ...
> "POC". Hmmm. Yes, that gets to the heart of the matter, as it seems to me you tend to assume that your audience has the same mindset as you do.

Well, I'm not removing functionality from `jq`, only adding. There are things I'd love to remove though. I can assume that `jq` will continue to work for those who don't care about a package manager, and that `jqnpm` works for those who like that kind of package manager.

> Of course one always has to make some assumptions about one's
> audience, but my hope for jq and associated tools is that they should
> be easy to use for someone who does not know much about command-line
> tools. For example, I have in mind someone who is proficient at using
> Word, Excel and R Studio, who knows a little about JSON, but for whom typing 
> "echo hello" at a command-line prompt is a stretch.

You're making a lot of assumptions, too. We're all expressing opinions.

"jq is a lightweight and flexible command-line JSON processor." They'd go elsewhere if they didn't want a CLI. Either way, building a GUI on top is easier than the other way around.

> b) The jqnpm script ought to allow it to be referenced as a symlink.

Resolved `$BASH_SOURCE` symlinks, should work from v0.5.3.

> ii) The installation instructions for jq-stress are:
> "After running the appropriate cd command to make your project/package directory the present working directory, ..."

I'd rather keep the package instructions short and sweet. If you discover the package before jqnpm itself, so be it - you'll have to get jqnpm first anyways. As you know, there's already "enough" text in the [`jqnpm`](https://github.com/joelpurra/jqnpm) repository README...

> Also, it's not clear what "your project/package directory" means. Is
> it the package subdirectory of my project, or is it my choice as to
> whether a project or package directory is used? What if I don't have
> a "project directory"?

This is very clear to me, having used `npm` a couple of years. I hope it'll be clear for the average `jqnpm` user too over time, as documentation improves.

> Anyway, the install command gives a rather scary warning:
> 
> $ cd jq/test
> $ jqnpm install joelpurra/jq-stress
> 
> jqnpm: [WARN]   folder (package) name does not start with 'jq-': 'test'
> Did I do something wrong? Do I have to start again? How would I go
> about doing that? What should I do differently? What if I don't do anything?

That warning is in place mostly with creating packages in mind. Guess I can remove it now that `jqnpm generate` works. See v0.5.4 and newer.

> ~/github/jqnpm/src/jqnpm execute -n 'import "joelpurra/jq-stress" as Stress; "Hello" | Stress::remove("e")'
> "Hllo"
> But a few seconds later ....
> 
> $ cd 
> $ ~/github/jqnpm/src/jqnpm execute -n 'import "joelpurra/jq-stress" as Stress; "Hello" | Stress::remove("e")'
> jq: error: module not found: joelpurra/jq-stress
> Now what? Should I have named the package "jq-joelpurra/jq-stress?"
> Where was that package installed? Can I use it outside the confines of the project directory? ....

Well, this is mostly due to the fact that you seem used to (and ok with) user-global packages being the default. I strongly prefer project-local packages. From v0.5.2 you can `jqnpm install --global joelpurra/jq-stress` to install in `${HOME}/.jq/packages/`. No modifications have to be done to `jq` #673, but I might make non-global `jqnpm` usage a bit stricter later.

If there's really a need for it, I might add `--system` as well.

> iv) The "Usage" section of the jq-stress documentation is long on
> examples, but raises more questions than it answers. Does "replace"
> replace once or multiple times? Why is isEmpty needed? Is it faster
> than using length?

You seem to focus on a very small part of a single package in this discussion. I've created [about ten other packages](https://github.com/joelpurra/jqnpm/wiki) you might want to look at as well. Patches are welcome, but for single-package questions please create issues in their respective repositories.

**Comment by joelpurra** [comment] 2015-01-22 09:56
Added a nice animation for a very basic jqnpm project demo. Created using shell-keystroke-animator.
https://github.com/joelpurra/shell-keystroke-animator
[![jqnpm-demo](https://cloud.githubusercontent.com/assets/1398544/5852881/aaefa09c-a21d-11e4-9e7b-7c2c5574e0b6.gif)](https://github.com/joelpurra/jqnpm)

(Ideally I wouldn't use `jqnpm execute`, only `jq`.)

@pkoppstein: what do you think? The `jqnpm init` step isn't even necessary, but because of it I can skip `mkdir jq`.

**Comment by pkoppstein** [comment] 2015-01-23 04:47
@joelpurra asked:
> What do you think?

The keystroke-animator is great, and the the gif animation must be worth at least 2,000 words. It makes your point succinctly.

Unfortunately, although I have a Mac running Mavericks, the keystroke-animator didn't quite work for me.  It doubled all the input keystrokes, and the output gif didn't include the output, even though it was (eventually) displayed on the screen.  Here is the "typescript":
```
keystroke-animator < ~/tmp/keys
keystroker: Now focus the window you want the typing to go in!
keystroker: 4...
keystroker: 3...
keystroker: 2...
keystroker: 1...
keystroker: 0...
keystroker: Keystrokes are echoed in this window:
nnppmm  vveerrssiioonn  ||  rruubbyy  ~~//bbiinn//jjss22jjssoonn..rrbb  ||  jjqq  ffrroommjjssoonn
```
Also -- a very small point, but while it's fresh in your mind, I would suggest slightly increasing the sleep time at the very end, or adding an option to increase the sleep time at the end (or both :-).  Thanks!

**Comment by joelpurra** [comment] 2015-01-23 06:51
@pkoppstein wrote:
> The keystroke-animator is great, and the the gif animation must be worth at least 2,000 words. It makes your point succinctly.

Great!

> It doubled all the input keystrokes

>> keystroker: Now focus the window you want the typing to go in!

You probably missed that part. It requires two windows; now you recorded the echoed input as well as the output, which means the command was run after the typing was done. It's been clarified.

> adding an option to increase the sleep time at the end

You probably won't have a problem with correct usage, but now added `endsleep`.

---

@pkoppstein: try this out:

```bash
brew tap joelpurra/joelpurra
brew install shell-keystroke-animator
```

Optionally `brew update` as well, just in case.

**Comment by dtolnay** [comment] 2015-07-25 19:59
@nicowilliams and @joelpurra, are you still planning on tackling this for 1.5? In the interest of finally getting a release out the door after more than a year, would it make sense to disable the module system, release 1.5, and wrap up modules for 1.6?

**Comment by pkoppstein** [comment] 2015-07-25 20:12
@dtolnay - Thanks again for all your work in support of getting jq ready for 1.5!

Regarding this particular thread -- the last comment prior to yours was on Jan 23.  Since then, the module system has been streamlined and I think there's agreement that it's ready for prime time (i.e. jq 1.5).  In fact it has been quite stable for a while  -- to my knowledge, since @nicowilliams added the finishing touches on June 27, no-one has requested a change to the module system for the 1.5 release.

**Comment by dtolnay** [comment] 2015-07-25 20:17
What about @joelpurra's PR #673? Do you know whether that is important for 1.5?

I have to admit I have not yet read through this thread and some of the other long modules-related threads.

**Comment by joelpurra** [comment] 2015-07-25 20:33
@dtolnay: thanks for your efforts indeed!

#673 is a great start for a working module system -- but currently outstanding features can wait until 1.6. I'll comment in #673 right away, before going to bed.

**Comment by dtolnay** [comment] 2015-07-25 20:37
Thanks Joel.

I will hold off on closing this until I read through and file issues for any remaining tasks.

**Comment by nicowilliams** [comment] 2015-07-25 20:44
I'll be back from a month of travel tomorrow and I'll review.

**Comment by joelpurra** [comment] 2015-07-25 20:57
@nicowilliams: great!

**Comment by joelpurra** [comment] 2015-07-25 20:58
@dtolnay: note that there are 160+ comments in related jq+jqnpm discussion threads; don't get lost in the rabbit hole ;)

**Comment by dtolnay** [comment] 2015-07-25 21:00
Thanks for the warning. Make sure you file issues for any remaining work you know about, in case I miss anything.

**Comment by pkoppstein** [comment] 2015-07-25 23:05
@dtolnay - I think the key here is @joelpurra's statement that "currently outstanding features can wait until 1.6."  From various remarks @nicowilliams made, I also believe that he intended that with the addition of 'include' on July 10, the module system was ready for the 1.5 release.

**Comment by nicowilliams** [comment] 2015-07-25 23:11
This is our last chance to make sure we're happy with the module system as
it is and that we've not perturbed ourselves into a corner.

**Closed** 2015-07-26 05:19 UTC
Labels: bug
